language: go

go:
  - "1.10.x"

git:
  depth: 1

go_import_path: wechat-miniprogram

install: true

services:
  - postgresql

notifications:
  email:
    - billstark1996@gmail.com

before_script:
  - ./setup
  - psql -c 'CREATE DATABASE mediocirs;' -U postgres
  - cp deploy/database.travis.yml config/database.yml

script:
  - go test ./...

jobs:
  include:
    - stage: build docker image
      script:
        - echo $TRAVIS_COMMIT
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker build -t wechat-miniprogram:${TRAVIS_COMMIT:0:7} .
        - docker tag wechat-miniprogram:${TRAVIS_COMMIT:0:7} $DOCKER_USERNAME/wechat-miniprogram
        - docker push $DOCKER_USERNAME/wechat-miniprogram