language: go

go:
  - "1.10.x"

git:
  depth: 1

go_import_path: wechat-miniprogram

install: true

services:
  - postgresql

notifications:
  email: false

before_script:
  - psql -c 'CREATE DATABASE mediocirs_test;' -U postgres
  - mkdir config && cp deploy/database.travis.yml config/database.yml

script:
  - go test ./...