language: go

go:
  - "1.10.x"

git:
  depth: 1

install: true

notifications:
  email: false

before_script:
  - go install ./vendor/github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - golangci-lint run
  - go test ./...