#!/bin/bash

# Exit on failures.
set -e

set -o pipefail

mkdir -p config

cp ./deploy/dbConfig.sample.json ./config/dbConfig.json
cp ./deploy/dbConfig.sample.json ./config/testDBConfig.json
cp ./deploy/serverConfig.sample.json ./config/serverConfig.json
