version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.8-jessie
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: test
          POSTGERS_DB: mediocirs
          POSTGERS_PASSWORD: test
    
    working_directory: /go/src/wechat-miniprogram

    steps:
      - checkout
      - run: ./setup
      - run: psql -c "CREATE DATABASE mediocirs;"" -U postgres
      - run: psql -c "CREATE ROLE test WITH LOGIN PASSWORD 'test'" -U postgres
      - run: tag=${CIRCLE_TAG:0:7}
      - run: go test ./...
      - run: docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - run: docker build -t wechat-miniprogram .
      - run: docker tag wechat-miniprogram $DOCKER_USERNAME/wechat-miniprogram:$tag
      - run: docker push $DOCKER_USERNAME/wechat-miniprogram:$tag