#!/bin/bash

# Exit on failures.
set -e

# Enable verbosity for easier debugging.
set -x

set -o pipefail

echo "Start setting up production config..."

SRC_DIR=/go/src/wechat-miniprogram
APP_DIR=/opt/wechat-miniprogram

mkdir -p $APP_DIR/config

source $SRC_DIR/utils/shell/templatefiller/jsontool

if [ -e $APP_DIR/secret.json ]
then

  # app configs
  echo "secret found. start running"
  json-template -s $APP_DIR/secret.json -f $SRC_DIR/utils/shell/templatefiller/fillin.jq \
                -i $SRC_DIR/deploy/dbConfig.template.json -o $APP_DIR/config/dbConfig.json
  json-template -s $APP_DIR/secret.json -f $SRC_DIR/utils/shell/templatefiller/fillin.jq \
                -i $SRC_DIR/deploy/serverConfig.template.json -o $APP_DIR/config/serverConfig.json

  echo "finish setting up config files"

  # nginx configs
  SECRET_STR=`cat $APP_DIR/secret.json`
  SERVER_HOST="$(jq '."<server_host>"' <<<"$SECRET_STR" | tr -d '"')"
  SERVER_PORT="$(jq '."<server_port>"' <<<"$SECRET_STR" | tr -d '"')"
  HOST_IP="$(jq '."<host_ip>"' <<<"$SECRET_STR" | tr -d '"')"
  HOST_PORT="$(jq '."<host_port>"' <<<"$SECRET_STR" | tr -d '"')"

  NGINX_CONFIG=`cat $SRC_DIR/deploy/wechatMiniprogram.template.nginx`
  NGINX_CONFIG="$(echo $NGINX_CONFIG | sed -e "s/\$SERVER_HOST/${SERVER_HOST}/g")"
  NGINX_CONFIG="$(echo $NGINX_CONFIG | sed -e "s/\$SERVER_PORT/${SERVER_PORT}/g")"
  NGINX_CONFIG="$(echo $NGINX_CONFIG | sed -e "s/\$HOST_IP/${HOST_IP}/g")"
  NGINX_CONFIG="$(echo $NGINX_CONFIG | sed -e "s/\$HOST_PORT/${HOST_PORT}/g")"

  echo $NGINX_CONFIG >> /etc/nginx/sites-available/wechatMiniprogram.nginx

  cp $SRC_DIR/deploy/nginx.conf /etc/nginx/nginx.conf
  ln -sf /etc/nginx/sites-available/wechatMiniprogram.nginx /etc/nginx/sites-enabled/wechatMiniprogram.nginx
  rm -f /etc/nginx/sites-enabled/default

  service nginx start &

  # logrotate for nginx.
  cp "$SRC_DIR/deploy/logrotate.nginx" /etc/logrotate.d

  # supervisor configs
  echo "setting up supervisor"
  
  cp $SRC_DIR/deploy/supervisord.conf /etc/supervisor/conf.d/wechat-miniprogram.conf
  echo "alias status='supervisorctl status'" >> ~/.bashrc
  echo "alias start='supervisorctl start wechat-miniprogram'" >> ~/.bashrc
  echo "alias restart='supervisorctl restart wechat-miniprogram'" >> ~/.bashrc
  echo "alias stop='supervisorctl stop wechat-miniprogram'" >> ~/.bashrc

  echo "Starting..."
  /usr/bin/supervisord -n
else
  echo "secret file does not exist"
  exit 1
fi